#!/usr/bin/env python
from venom_perception.TrajPredict import load_data
import argparse
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Trajctory Prediction')
    parser.add_argument('-d', '--data',help='data direcotry', required=True)
    datapath = parser.parse_args().data
    X, y = load_data(datapath, 4)
    print X.shape
    print y.shape

